/**
 *
 *  @file FrontendResult.hpp
 *  @author Gaspard Kirira
 *
 *  Copyright (c) 2026 Gaspard Kirira.
 *  https://github.com/vixcpp/vixc
 *
 *  Licensed under the MIT License.
 *  See LICENSE in the project root for license information.
 *
 *  VixC
 *
 */

#if !defined(VIXC_FRONTEND_RESULT_HPP)
#define VIXC_FRONTEND_RESULT_HPP

#include <vixc/Diagnostic.hpp>
#include <vixc/FrontendOptions.hpp>
#include <vixc/SourceRange.hpp>

#include <cstddef>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace vixc
{

  /**
   * @brief Maps a generated output range back to original source.
   *
   * GeneratedSourceMapping is the public representation of source provenance
   * produced by the frontend.
   *
   * The generated range uses zero-based byte offsets into the generated output
   * stored by FrontendResult. The original range refers to the source unit that
   * caused the generated bytes to be emitted.
   *
   * Generated ranges use half-open semantics. generated_begin is inclusive and
   * generated_end is exclusive.
   *
   * A mapping records provenance rather than textual equivalence. Generated and
   * original ranges may therefore have different sizes.
   */
  struct GeneratedSourceMapping final
  {
    /**
     * @brief Inclusive byte offset in generated output.
     */
    std::size_t generated_begin{0};

    /**
     * @brief Exclusive byte offset in generated output.
     */
    std::size_t generated_end{0};

    /**
     * @brief Original source range represented by the generated interval.
     */
    SourceRange original_range{};

    /**
     * @brief Reports whether the mapping is structurally valid.
     *
     * @return true when the original range is valid and the generated interval
     *         is ordered correctly.
     */
    [[nodiscard]]
    constexpr bool valid() const noexcept
    {
      return original_range.valid() && generated_begin <= generated_end;
    }

    /**
     * @brief Returns the number of generated bytes covered by the mapping.
     *
     * Invalid mappings return zero.
     *
     * @return Generated range size in bytes.
     */
    [[nodiscard]]
    constexpr std::size_t generated_size() const noexcept
    {
      if (!valid())
        return 0;

      return generated_end - generated_begin;
    }

    /**
     * @brief Reports whether a generated byte offset belongs to this mapping.
     *
     * @param offset Generated byte offset to test.
     *
     * @return true when the offset lies inside the half-open generated range.
     */
    [[nodiscard]]
    constexpr bool contains(std::size_t offset) const noexcept
    {
      return valid() && offset >= generated_begin && offset < generated_end;
    }
  };

  /**
   * @brief Result returned by one VixC frontend invocation.
   *
   * FrontendResult contains the externally observable result of processing a
   * source unit through the VixC frontend.
   *
   * It records whether the requested frontend action completed successfully,
   * the action and backend configuration used for the invocation, all
   * diagnostics produced during processing, and generated output when emission
   * was requested.
   *
   * FrontendResult owns its diagnostics and generated output. It does not retain
   * references to the internal SourceManager, parser, semantic analyzer, IR,
   * lowering pipeline, or backend objects used to produce the result.
   *
   * This makes the result safe to return from Frontend after the internal
   * frontend operation has completed.
   *
   * For FrontendAction::Analyze, generated_output() is normally empty because
   * the frontend stops after semantic analysis.
   *
   * For FrontendAction::Lower, generated_output() is also normally empty because
   * the backend-independent IR is lowered internally but no backend emission is
   * requested.
   *
   * For FrontendAction::Emit, generated_output() contains the output produced by
   * the selected backend when processing succeeds.
   *
   * The first VixC generation uses BackendTarget::Cxx, so emitted output is
   * ordinary C++ source.
   *
   * Source mappings are included when FrontendOptions::retain_source_map is
   * enabled and the selected backend provides textual source provenance.
   */
  class FrontendResult final
  {
  public:
    /**
     * @brief Creates an empty unsuccessful frontend result.
     *
     * The default result contains no diagnostics, generated output, or source
     * mappings.
     */
    FrontendResult() = default;

    /**
     * @brief Creates a complete frontend result.
     *
     * All supplied collections and generated output are moved into the result.
     *
     * @param success Whether the requested frontend action completed
     *        successfully.
     * @param action Frontend action requested by the caller.
     * @param backend Backend selected for emission.
     * @param diagnostics Diagnostics produced during frontend processing.
     * @param generated_output Generated backend output, when available.
     * @param source_mappings Generated-to-original source mappings.
     */
    FrontendResult(
        bool success,
        FrontendAction action,
        BackendTarget backend,
        std::vector<Diagnostic> diagnostics,
        std::string generated_output = {},
        std::vector<GeneratedSourceMapping> source_mappings = {})
        : success_(success),
          action_(action),
          backend_(backend),
          diagnostics_(std::move(diagnostics)),
          generated_output_(std::move(generated_output)),
          source_mappings_(std::move(source_mappings))
    {
    }

    FrontendResult(const FrontendResult &) = default;
    FrontendResult &operator=(const FrontendResult &) = default;

    FrontendResult(FrontendResult &&) noexcept = default;
    FrontendResult &operator=(FrontendResult &&) noexcept = default;

    ~FrontendResult() = default;

    /**
     * @brief Reports whether the requested frontend action succeeded.
     *
     * Success means the frontend completed the requested action without Error
     * or Fatal diagnostics.
     *
     * @return true when the frontend operation succeeded.
     */
    [[nodiscard]]
    bool success() const noexcept
    {
      return success_;
    }

    /**
     * @brief Converts the result to a success boolean.
     *
     * @return Same value as success().
     */
    [[nodiscard]]
    explicit operator bool() const noexcept
    {
      return success();
    }

    /**
     * @brief Returns the frontend action performed for this result.
     *
     * @return Requested frontend action.
     */
    [[nodiscard]]
    FrontendAction action() const noexcept
    {
      return action_;
    }

    /**
     * @brief Returns the backend selected for this frontend invocation.
     *
     * The value remains available for Analyze and Lower results even though no
     * backend emission was requested.
     *
     * @return Configured backend target.
     */
    [[nodiscard]]
    BackendTarget backend() const noexcept
    {
      return backend_;
    }

    /**
     * @brief Returns all diagnostics produced by the frontend.
     *
     * Diagnostics remain in frontend emission order.
     *
     * @return Read-only diagnostic collection.
     */
    [[nodiscard]]
    const std::vector<Diagnostic> &
    diagnostics() const noexcept
    {
      return diagnostics_;
    }

    /**
     * @brief Returns the number of diagnostics in the result.
     *
     * @return Number of stored diagnostics.
     */
    [[nodiscard]]
    std::size_t diagnostic_count() const noexcept
    {
      return diagnostics_.size();
    }

    /**
     * @brief Reports whether the result contains any diagnostics.
     *
     * @return true when at least one diagnostic is stored.
     */
    [[nodiscard]]
    bool has_diagnostics() const noexcept
    {
      return !diagnostics_.empty();
    }

    /**
     * @brief Reports whether the result contains an Error or Fatal diagnostic.
     *
     * @return true when at least one diagnostic represents an error.
     */
    [[nodiscard]]
    bool has_errors() const noexcept
    {
      for (const Diagnostic &diagnostic : diagnostics_)
      {
        if (diagnostic.is_error())
          return true;
      }

      return false;
    }

    /**
     * @brief Reports whether the result contains a Fatal diagnostic.
     *
     * @return true when at least one diagnostic is fatal.
     */
    [[nodiscard]]
    bool has_fatal() const noexcept
    {
      for (const Diagnostic &diagnostic : diagnostics_)
      {
        if (diagnostic.is_fatal())
          return true;
      }

      return false;
    }

    /**
     * @brief Returns the generated backend output.
     *
     * The first VixC generation returns ordinary C++ when emission uses
     * BackendTarget::Cxx.
     *
     * Analyze and Lower operations normally return an empty view.
     *
     * @return Non-owning view of generated backend output.
     */
    [[nodiscard]]
    std::string_view generated_output() const noexcept
    {
      return generated_output_;
    }

    /**
     * @brief Reports whether backend output was generated.
     *
     * @return true when generated_output() is not empty.
     */
    [[nodiscard]]
    bool has_generated_output() const noexcept
    {
      return !generated_output_.empty();
    }

    /**
     * @brief Returns the generated output size in bytes.
     *
     * @return Number of bytes in generated_output().
     */
    [[nodiscard]]
    std::size_t generated_output_size() const noexcept
    {
      return generated_output_.size();
    }

    /**
     * @brief Returns generated-to-original source mappings.
     *
     * Mappings are stored in generated output order.
     *
     * The collection may be empty when source-map retention was disabled, when
     * no backend output was generated, or when generated bytes have no direct
     * original source provenance.
     *
     * @return Read-only source mapping collection.
     */
    [[nodiscard]]
    const std::vector<GeneratedSourceMapping> &
    source_mappings() const noexcept
    {
      return source_mappings_;
    }

    /**
     * @brief Reports whether generated source mappings are available.
     *
     * @return true when at least one source mapping is stored.
     */
    [[nodiscard]]
    bool has_source_mappings() const noexcept
    {
      return !source_mappings_.empty();
    }

    /**
     * @brief Finds the original source range for a generated byte offset.
     *
     * Mappings are non-overlapping and stored in generated order. The function
     * returns the first mapping containing the requested generated byte.
     *
     * @param generated_offset Byte offset in generated_output().
     *
     * @return Pointer to the matching original SourceRange, or nullptr when the
     *         generated byte has no source mapping.
     */
    [[nodiscard]]
    const SourceRange *
    original_range_for(
        std::size_t generated_offset) const noexcept
    {
      for (const GeneratedSourceMapping &mapping : source_mappings_)
      {
        if (mapping.contains(generated_offset))
          return &mapping.original_range;

        if (mapping.generated_begin > generated_offset)
          break;
      }

      return nullptr;
    }

  private:
    /// Whether the requested frontend action completed successfully.
    bool success_{false};

    /// Frontend action requested for this invocation.
    FrontendAction action_{FrontendAction::Emit};

    /// Backend target configured for this invocation.
    BackendTarget backend_{BackendTarget::Cxx};

    /// Structured diagnostics produced during frontend processing.
    std::vector<Diagnostic> diagnostics_;

    /// Generated backend output owned by this result.
    std::string generated_output_;

    /// Generated-to-original source provenance retained for the result.
    std::vector<GeneratedSourceMapping> source_mappings_;
  };

} // namespace vixc

#endif // VIXC_FRONTEND_RESULT_HPP
