
/**
 *
 *  @file CxxSourceMap.hpp
 *  @author Gaspard Kirira
 *
 *  Copyright (c) 2026 Gaspard Kirira.
 *  https://github.com/vixcpp/vixc
 *
 *  Licensed under the MIT License.
 *  See LICENSE in the project root for license information.
 *
 *  VixC
 *
 */

#if !defined(VIXC_BACKENDS_CXX_CXX_SOURCE_MAP_HPP)
#define VIXC_BACKENDS_CXX_CXX_SOURCE_MAP_HPP

#include <vixc/SourceRange.hpp>

#include <cstddef>
#include <optional>
#include <vector>

namespace vixc::backends::cxx
{
  /**
   * @brief Associates one generated C++ byte range with original VixC source.
   *
   * CxxSourceMapEntry records a half-open byte interval in the generated C++
   * output and the SourceRange from which that interval originated.
   *
   * Generated offsets are zero-based byte offsets into the complete C++ source
   * emitted by the backend.
   *
   * The original range always refers to source managed by the VixC frontend.
   * It may represent source copied directly from an ordinary C++ region or a
   * VixC construct whose generated representation corresponds to that original
   * semantic operation.
   *
   * Source-map entries describe provenance. They do not imply that generated
   * and original ranges have the same size or textual spelling.
   */
  class CxxSourceMapEntry final
  {
  public:
    /**
     * @brief Creates an invalid source-map entry.
     */
    constexpr CxxSourceMapEntry() noexcept = default;

    /**
     * @brief Creates a mapping between generated C++ and original source.
     *
     * @param generated_begin Inclusive byte offset in generated C++.
     * @param generated_end Exclusive byte offset in generated C++.
     * @param original_range Original VixC source range represented by the
     *        generated interval.
     */
    constexpr CxxSourceMapEntry(
        std::size_t generated_begin,
        std::size_t generated_end,
        SourceRange original_range) noexcept
        : generated_begin_(generated_begin),
          generated_end_(generated_end),
          original_range_(original_range)
    {
    }

    /**
     * @brief Returns the inclusive generated byte offset.
     *
     * @return Beginning byte offset in generated C++.
     */
    [[nodiscard]]
    constexpr std::size_t generated_begin() const noexcept
    {
      return generated_begin_;
    }

    /**
     * @brief Returns the exclusive generated byte offset.
     *
     * @return Ending byte offset in generated C++.
     */
    [[nodiscard]]
    constexpr std::size_t generated_end() const noexcept
    {
      return generated_end_;
    }

    /**
     * @brief Returns the number of generated bytes covered by this entry.
     *
     * Invalid entries return zero.
     *
     * @return Generated range length in bytes.
     */
    [[nodiscard]]
    constexpr std::size_t generated_size() const noexcept
    {
      if (!valid())
        return 0;

      return generated_end_ - generated_begin_;
    }

    /**
     * @brief Returns the original source range represented by this entry.
     *
     * @return Original VixC source range.
     */
    [[nodiscard]]
    constexpr SourceRange original_range() const noexcept
    {
      return original_range_;
    }

    /**
     * @brief Reports whether the entry satisfies its structural invariants.
     *
     * A valid entry requires a valid original source range and a generated
     * interval whose beginning does not exceed its end.
     *
     * Zero-length generated ranges are structurally valid. They can represent a
     * generated position associated with a zero-length source operation.
     *
     * @return true when the entry is structurally valid.
     */
    [[nodiscard]]
    constexpr bool valid() const noexcept
    {
      return original_range_.valid() && generated_begin_ <= generated_end_;
    }

    /**
     * @brief Reports whether a generated byte offset lies inside this entry.
     *
     * The generated interval uses half-open semantics. generated_begin() is
     * included while generated_end() is excluded.
     *
     * A zero-length entry contains no byte offset.
     *
     * @param offset Generated C++ byte offset to test.
     *
     * @return true when the offset lies inside the generated interval.
     */
    [[nodiscard]]
    constexpr bool contains(std::size_t offset) const noexcept
    {
      return valid() && offset >= generated_begin_ && offset < generated_end_;
    }

  private:
    /// Inclusive generated C++ byte offset.
    std::size_t generated_begin_{0};

    /// Exclusive generated C++ byte offset.
    std::size_t generated_end_{0};

    /// Original VixC source represented by the generated interval.
    SourceRange original_range_{};
  };

  /**
   * @brief Tracks provenance between generated C++ and original VixC source.
   *
   * CxxSourceMap is built incrementally while the C++ backend emits output.
   * Each entry records which original source range produced a region of the
   * generated C++ translation unit.
   *
   * The map allows diagnostics from later stages of the native compilation
   * pipeline to be related back to the source that VixC processed. It also
   * supports debugging, generated-code inspection, tests, and future tooling
   * that needs to understand the relationship between VixC constructs and
   * emitted C++.
   *
   * Entries are stored in generated-source order. The C++ emitter is expected to
   * add mappings monotonically as output is appended.
   *
   * Not every generated byte must have a source-map entry. Backend-generated
   * support code, whitespace, declarations, or implementation details may have
   * no direct source equivalent.
   *
   * Likewise, a source range may correspond to generated text of a different
   * size. CxxSourceMap records provenance rather than character-for-character
   * transformation.
   */
  class CxxSourceMap final
  {
  public:
    /**
     * @brief Creates an empty source map.
     */
    CxxSourceMap() = default;

    /**
     * @brief Adds one generated-to-original source mapping.
     *
     * The generated interval follows half-open semantics.
     *
     * Invalid entries are rejected.
     *
     * Entries must be added in nondecreasing generated offset order. A new
     * mapping may begin at or after the end of the previous mapping. Overlapping
     * generated ranges are rejected so lookup remains deterministic.
     *
     * @param generated_begin Inclusive generated C++ byte offset.
     * @param generated_end Exclusive generated C++ byte offset.
     * @param original_range Original VixC source range.
     *
     * @return true when the mapping is accepted, otherwise false.
     */
    [[nodiscard]]
    bool add(
        std::size_t generated_begin,
        std::size_t generated_end,
        SourceRange original_range);

    /**
     * @brief Adds a complete source-map entry.
     *
     * This overload follows the same validity and ordering requirements as the
     * offset-based add() function.
     *
     * @param entry Source-map entry to append.
     *
     * @return true when the entry is accepted, otherwise false.
     */
    [[nodiscard]]
    bool add(CxxSourceMapEntry entry);

    /**
     * @brief Finds the mapping containing a generated byte offset.
     *
     * Because generated mappings do not overlap, at most one entry can contain
     * the requested byte offset.
     *
     * @param generated_offset Byte offset in the emitted C++ source.
     *
     * @return Pointer to the matching entry, or nullptr when the generated byte
     *         has no source mapping.
     */
    [[nodiscard]]
    const CxxSourceMapEntry *
    find(std::size_t generated_offset) const noexcept;

    /**
     * @brief Returns the original source range associated with a generated byte.
     *
     * This is a convenience wrapper around find().
     *
     * @param generated_offset Byte offset in emitted C++.
     *
     * @return Original source range, or std::nullopt when no mapping exists.
     */
    [[nodiscard]]
    std::optional<SourceRange>
    original_range_for(
        std::size_t generated_offset) const noexcept;

    /**
     * @brief Returns all mappings in generated-source order.
     *
     * @return Read-only source-map entries.
     */
    [[nodiscard]]
    const std::vector<CxxSourceMapEntry> &
    entries() const noexcept;

    /**
     * @brief Returns the number of source-map entries.
     *
     * @return Number of stored mappings.
     */
    [[nodiscard]]
    std::size_t size() const noexcept;

    /**
     * @brief Reports whether the source map contains no mappings.
     *
     * @return true when size() is zero.
     */
    [[nodiscard]]
    bool empty() const noexcept;

    /**
     * @brief Removes every generated-source mapping.
     *
     * The CxxSourceMap can be reused after clearing.
     */
    void clear() noexcept;

  private:
    /// Generated-to-original mappings in generated source order.
    std::vector<CxxSourceMapEntry> entries_;
  };

} // namespace vixc::backends::cxx

#endif // VIXC_BACKENDS_CXX_CXX_SOURCE_MAP_HPP
