/**
 *
 *  @file TranspilerTest.cpp
 *  @author Gaspard Kirira
 *
 *  Copyright 2026, Gaspard Kirira.
 *  All rights reserved.
 *  https://github.com/vixcpp/vixc
 *
 *  Use of this source code is governed by a MIT license
 *  that can be found in the License file.
 *
 *  Vix++
 *
 */

#include <vixc/Diagnostic.hpp>
#include <vixc/Transpiler.hpp>

#include <cstdlib>
#include <iostream>
#include <string>

namespace
{
  int failures = 0;

  void expect_true(bool value, const std::string &message)
  {
    if (!value)
    {
      ++failures;
      std::cerr << "FAIL: " << message << '\n';
    }
  }

  void expect_false(bool value, const std::string &message)
  {
    expect_true(!value, message);
  }

  void expect_contains(const std::string &text,
                       const std::string &needle,
                       const std::string &message)
  {
    if (text.find(needle) == std::string::npos)
    {
      ++failures;
      std::cerr << "FAIL: " << message << '\n'
                << "  missing: " << needle << '\n'
                << "  text:\n"
                << text << '\n';
    }
  }

  void expect_not_contains(const std::string &text,
                           const std::string &needle,
                           const std::string &message)
  {
    if (text.find(needle) != std::string::npos)
    {
      ++failures;
      std::cerr << "FAIL: " << message << '\n'
                << "  unexpected: " << needle << '\n'
                << "  text:\n"
                << text << '\n';
    }
  }

  void expect_eq_size(std::size_t actual,
                      std::size_t expected,
                      const std::string &message)
  {
    if (actual != expected)
    {
      ++failures;
      std::cerr << "FAIL: " << message << '\n'
                << "  expected: " << expected << '\n'
                << "  actual  : " << actual << '\n';
    }
  }

  void test_basic_imports()
  {
    const std::string source =
        "use vix.http;\n"
        "use std.iostream;\n"
        "\n"
        "int main()\n"
        "{\n"
        "  return 0;\n"
        "}\n";

    vixc::DiagnosticBag diagnostics{};
    vixc::Transpiler transpiler{};

    const auto result = transpiler.transpile_string(source, diagnostics, "basic.vix");

    expect_false(diagnostics.has_errors(), "basic imports should not emit errors");
    expect_true(result.has_code(), "basic imports should generate code");
    expect_eq_size(result.imports.size(), 2, "basic imports count");

    expect_contains(result.code, "// Generated by Vix++. Do not edit directly.", "generated banner");
    expect_contains(result.code, "#include <vix/http.hpp>", "vix.http include");
    expect_contains(result.code, "#include <iostream>", "std.iostream include");
    expect_contains(result.code, "int main()", "body should be preserved");
    expect_not_contains(result.code, "use vix.http;", "use line should be removed");
  }

  void test_duplicate_imports_are_deduplicated()
  {
    const std::string source =
        "use vix.json;\n"
        "use vix.json;\n"
        "\n"
        "int main() { return 0; }\n";

    vixc::DiagnosticBag diagnostics{};
    vixc::Transpiler transpiler{};

    const auto result = transpiler.transpile_string(source, diagnostics, "dups.vix");

    expect_false(diagnostics.has_errors(), "duplicate imports should not emit errors");
    expect_eq_size(result.imports.size(), 1, "duplicate imports should be deduplicated");
    expect_contains(result.code, "#include <vix/json.hpp>", "deduplicated vix.json include");
  }

  void test_comments_before_imports_are_allowed()
  {
    const std::string source =
        "// comment before imports\n"
        "\n"
        "use std.vector;\n"
        "\n"
        "int main() { return 0; }\n";

    vixc::DiagnosticBag diagnostics{};
    vixc::Transpiler transpiler{};

    const auto result = transpiler.transpile_string(source, diagnostics, "comments.vix");

    expect_false(diagnostics.has_errors(), "comments before imports should be allowed");
    expect_contains(result.code, "#include <vector>", "std.vector include");
    expect_contains(result.code, "// comment before imports", "comment should be preserved");
  }

  void test_import_after_code_is_error()
  {
    const std::string source =
        "int main()\n"
        "{\n"
        "  return 0;\n"
        "}\n"
        "use vix.http;\n";

    vixc::DiagnosticBag diagnostics{};
    vixc::Transpiler transpiler{};

    const auto result = transpiler.transpile_string(source, diagnostics, "late.vix");

    expect_true(diagnostics.has_errors(), "late import should emit an error");
    expect_true(result.has_code(), "late import still returns generated code for diagnostics/debug");
    expect_contains(result.code, "use vix.http;", "late invalid use line should remain in body");
  }

  void test_local_import()
  {
    const std::string source =
        "use local.config;\n"
        "\n"
        "int main() { return 0; }\n";

    vixc::DiagnosticBag diagnostics{};
    vixc::Transpiler transpiler{};

    const auto result = transpiler.transpile_string(source, diagnostics, "local.vix");

    expect_false(diagnostics.has_errors(), "local import should not emit errors");
    expect_contains(result.code, "#include \"config.hpp\"", "local.config include");
  }

  void test_invalid_import_name()
  {
    const std::string source =
        "use vix..http;\n"
        "\n"
        "int main() { return 0; }\n";

    vixc::DiagnosticBag diagnostics{};
    vixc::Transpiler transpiler{};

    const auto result = transpiler.transpile_string(source, diagnostics, "invalid.vix");

    expect_true(diagnostics.has_errors(), "invalid import name should emit an error");
    expect_true(result.has_code(), "invalid import should still produce generated output");
  }
}

int main()
{
  test_basic_imports();
  test_duplicate_imports_are_deduplicated();
  test_comments_before_imports_are_allowed();
  test_import_after_code_is_error();
  test_local_import();
  test_invalid_import_name();

  if (failures != 0)
  {
    std::cerr << failures << " test failure(s)\n";
    return EXIT_FAILURE;
  }

  std::cout << "Transpiler tests passed\n";
  return EXIT_SUCCESS;
}
